// Work types for this board — the "what kind of work is this?" axis on a task,
// shown as a chip and a filter in the Tasks tab and written into the task title
// as a bracket tag (`[Ship]`).
//
// GENERATED by .claude/scripts/setup/apply-work-types.mjs for role: ic-engineer
// (Individual contributor — the four things that actually eat an engineer's week)
//
// Yours to edit. Re-running the script overwrites the file, so if you change the
// buckets by hand, don't re-run it. Renaming a `tag` does NOT rewrite existing
// task lines — grep content/tasks/ for the old tag if you rename one.
//
// Constraints the dashboard enforces at startup: at least one entry, and unique
// slug / tag / emoji across the set.
import type { WorkTypeDef } from '@asucregonzalez/section-tasks';

export const WORK_TYPES: WorkTypeDef[] = [
  { slug: "ship",    tag: "Ship",    name: "Ship",    emoji: "📦", color: "#06b6d4" },
  { slug: "quality", tag: "Quality", name: "Quality", emoji: "🧪", color: "#22c55e" },
  { slug: "support", tag: "Support", name: "Support", emoji: "🆘", color: "#f43f5e" },
  { slug: "growth",  tag: "Growth",  name: "Growth",  emoji: "📚", color: "#8b5cf6" },
];
